name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^8.1.6

  #comparing dart objects
  equatable: ^2.0.8

  #service locator
  get_it: ^8.3.0
  
  #dateFormat
  intl: ^0.18.1

  #Database
  #floor: ^1.5.0
  #floor_annotation: ^1.5.0

  #make request to api
  retrofit: ^4.9.2

  # Firebase
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0




  #Hooks
  flutter_hooks: ^0.18.6

  #chached image 
  cached_network_image: ^3.4.1

  #json
  json_annotation: ^4.9.0

  #database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
  #floor_generator: ^1.5.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:21, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    backgroundColor: "#1A1A40"
    themeColor: "#1A1A40"

flutter_native_splash:
  color: "#1A1A40"
  image: "assets/images/app_logo.png"
  android: true
  ios: true
  web: false
  
  # Especial para Android 12+
  android_12:
    color: "#1A1A40"
    image: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
